spring:
  profiles:
    active: dev
  security:
    jwt:
      key: abcdefghijklmnopqrstuvwxyz
      expire: 72  # JWT令牌过期时间，以小时为单位
      limit:
        base: 10  # 用户生成JWT令牌的基础冷却时间，以秒为单位
        upgrade: 300  # 恶意刷令牌的惩罚时间，以秒为单位
        frequency: 30  # 判定为恶意刷令牌的阈值次数