spring:
  profiles:
    active: dev
  security:
    jwt:
      key: abcdefghijklmnopqrstuvwxyz
      expire: 72  # JWT令牌过期时间，以小时为单位
      limit:
        base: 10  # 用户生成JWT令牌的基础冷却时间，以秒为单位
        upgrade: 300  # 恶意刷令牌的惩罚时间，以秒为单位
        frequency: 30  # 判定为恶意刷令牌的阈值次数
  web:
    flow:
      limit: 20  # 单个IP在时间段内最大请求次数
      period: 1  # 计数时间周期（秒）
      block: 30  # 超出请求限制后封禁时间（秒）

  minio:
    endpoint: 'http://127.0.0.1:54722'
    username: 'minioadmin'
    password: 'minioadmin'
